package features

enum class Feature(val tags: Array<String>) {
    NATURE(
        arrayOf(
            "leisure=park",
            "tourism=theme_park",
            "tourism=zoo",
            "tourism=viewpoint",
            "leisure=nature_reserve",
            "tourism=picnic_site",
            "leisure=park",
            "amenity=grave_yard",
            "barrier=hedge",
            "building=tree_house",
            "landuse=farmland",
            "landuse=forest",
            "landuse=meadow",
            "landuse=orchard",
            "landuse=vineyard",
            "man_made=clearcut",
            "natural~'[a-z]*'"
        )
    ),
    CULTURE(
        arrayOf(
            "amenity=cinema",
            "tourism~'[a-z]*'",
            "amenity = theatre",
            "building=church",
            "building=cathedral",
            "amenity=arts_centre",
            "building=church",
            "landuse=religious",
            "building=government",
            "building=culture",
            "building=civic",
            "building=university",
            "building=castle",
            "building=ruins"
        )
    ),
    SHOPPING(
        arrayOf(
            "building=supermarket",
            "building=kiosk",
            "shop~'[a-z]*'",
            "amenity=marketplace",
            "building=retail",
            "building=commercial"
        )
    ),
    FUN_SPORTS(
        arrayOf(
            "leisure~'[a-z]*'",
            "sport~'[a-z]*'",
            "amenity=nightclub",
            "building=grandstand",
            "building=sports_hall",
            "building=stadium"
        )
    ),
    RESTAURANTS(
        arrayOf(
            "amenity=biergarten",
            "amenity=cafe",
            "amenity=fast_food",
            "amenity=bar",
            "amenity=restaurant",
            "amenity=food_court",
            "amenity=ice_cream",
            "amenity=ice_cream"
        )
    ),
    PUBLIC_TRANSPORT(
        arrayOf(
            "building=transportation",
            "building=train_station",
            "amenity=bus_station",
            "public_transport~'[a-z]*'"
        )
    )
}
